assignment1/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^word_bank/',include('word_bank.urls')),
    url(r'^',include('home.urls')),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$',views.home_page, name= 'home_page'),
]

word_bank/urls.py
from django.conf.urls import  url
from . import views

app_name = 'word_bank'
urlpatterns = [
    url(r'^$',views.index , name = 'index'),
    url(r'^find_word/$',views.find_word, name = 'find_word'),
    url(r'^add_word_page/$',views.add_word_page, name = 'add_word_page'),
    url(r'^show_all_word/$',views.show_all_word, name = 'show_all_word'),
    url(r'^(?P<word_text>[a-z]+)/detail/$',views.detail, name='detail'),
    url(r'^save_load_csv_page/$',views.save_load_csv_page, name='save_load_csv_page'),
    url(r'^load_csv_file/$',views.load_csv_file, name='load_csv_file'),
    url(r'^save_csv_file/$',views.save_csv_file, name='save_csv_file'),
    url(r'^save_xml_file/$', views.save_xml_file, name='save_xml_file'),
    url(r'^load_xml_file/$', views.load_xml_file, name='load_xml_file'),
    url(r'^write_upload_file_for_load_word/$', views.write_upload_file_for_load_word, name='write_upload_file_for_load_word'),
    url(r'^standard_load_xml_file/$', views.standard_load_xml_file, name='standard_load_xml_file'),
    url(r'^standard_save_xml_file/$', views.standard_save_xml_file, name='standard_save_xml_file'),


]

word_bank/models.py
from django.db import models

# Create your models here.
class Word(models.Model):
    word_text = models.CharField(max_length = 200)
    search_count = models.IntegerField(default=0)
    last_search_date = models.DateTimeField('date published')
    def __str__(self):
        return self.word_text

class Meaning(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    meaning_text = models.CharField(max_length = 200)
    meaning_type = models.CharField(max_length = 10)
    sample_sentence_text = models.CharField(max_length = 200)

    def __str__(self):
        return '({}) '.format(self.meaning_type)+self.meaning_text+' : '+self.sample_sentence_text

word_bank/views.py
from django.shortcuts import render,get_object_or_404
from word_bank.models import Word
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
import csv
from django.utils.encoding import smart_str
import os
from django.contrib.staticfiles.templatetags.staticfiles import static
import xml.etree.ElementTree as ET
from django.utils import timezone

# Create your views here.
def index(request):
    request.session['load'] = ''
    all_word = Word.objects.order_by('-search_count')[:4]  # get object is search by user often only 4 words
    last_words = Word.objects.order_by('-last_search_date')[:4]  # get objects is search lastest only 4 words
    context = {'all_word':all_word,'last_words':last_words}
    return render(request,'word_bank/index.html',context)

def find_word(request):
    word_search = request.GET['word']
    words = Word.objects.filter(word_text__startswith = word_search)  # return list of objects words
    if (len(words) == 1) and (words[0].word_text == word_search):  # have only 1 word and word_text match go to detail page
        return HttpResponseRedirect(reverse('word_bank:detail',kwargs={'word_text': words[0].word_text }))
    else:  # return more 1 words
        context = {'words':words,'word_search':word_search}
        return render(request,'word_bank/find_word.html',context)


def add_word_page(request):
    error_message = ''  # for display error message on page
    if request.method == 'POST':
        word_text_form = request.POST['word']
        meaning_text_form = request.POST['meaning']
        meaning_type_text_form = request.POST['meaning_type']
        sample_sentence_text_form = request.POST['sample_sentence']

        if Word.objects.filter(word_text=word_text_form):  # do if have any objects same name
            word = Word.objects.get(word_text=word_text_form)
            if not word.meaning_set.filter(meaning_text=meaning_text_form):  # if not have same meaning , create new meaning
                word.meaning_set.create(meaning_text=meaning_text_form,meaning_type=meaning_type_text_form,sample_sentence_text=sample_sentence_text_form)
                error_message = 'add new your meaning complete'
            else:
                error_message = 'have same meaning already'

        else:  # not same name can create new word
            word = Word(word_text=word_text_form)
            word.save()
            word.meaning_set.create(meaning_text=meaning_text_form,meaning_type=meaning_type_text_form,sample_sentence_text=sample_sentence_text_form)
            error_message = 'Add Your New Word Completely'
    context = {'error_message':error_message}
    return render(request,'word_bank/add_word_page.html',context)

def show_all_word(request):
    all_word = Word.objects.order_by('word_text')
    context = {'all_word':all_word}
    return render(request,'word_bank/show_all_word.html',context)

def detail(request, word_text):
    word = get_object_or_404(Word, word_text=word_text)  # return word object or 404
    word.search_count = word.search_count + 1  # plus search counter by 1 for measument frequently
    word.last_search_date = timezone.now()  # set last_search_date is timezone now
    word.save()
    print(word.search_count)
    context = {'word':word}
    return render(request,'word_bank/detail.html',context)

def save_load_csv_page(request):
    return render(request,'word_bank/save_load_csv_page.html')

def load_csv_file(request):
    #dirPath = 'word_bank/static/word_bank/load_csv/'
    #if request.FILES != {}:  # if have file uploaded
        #csvFile = request.FILES['csvFile']
        #saveFilePath = default_storage.save(dirPath,csvFile)
        #os.rename(saveFilePath,'{}{}'.format(dirPath,csvFile.name))
    all_word = Word.objects.all()
    for word in all_word:
        word.delete()  # delete all before read word in csv
    with open(request.session['load']) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['word'] != '':
                if Word.objects.filter(word_text=row['word']):
                    word = Word.objects.get(word_text=row['word'])
                else:
                    word = Word(word_text=row['word'])
                    word.save()
            else:
                if not word.meaning_set.filter(meaning_text=row['meaning']):  # if not have same meaning , create new meaning
                    word.meaning_set.create(meaning_text=row['meaning'], meaning_type=row['type'], sample_sentence_text=row['sample_sentence'])
    request.session['load'] = 'Words have been loaded successfully!'  # show loaded messeage at save_load_csv_file page
    return HttpResponseRedirect(reverse('word_bank:save_load_csv_page'))
    #else:
       # request.session['load'] = 'No File To Upload'
        #return HttpResponseRedirect(reverse('word_bank:save_load_csv_page'))  # not read file if haven't file uploaded

def load_xml_file(request):
    all_word = Word.objects.all()
    for word in all_word:
        word.delete()  # delete all before read word in xml
    tree = ET.parse(request.session['load'])  # read file form backup_xml
    words = tree.getroot()
    for et_word in words:
        if Word.objects.filter(word_text=et_word.attrib['word_text']):  # check name object is same already or not
            word = Word.objects.get(word_text=et_word.attrib['word_text'])
        else:
            word = Word(word_text=et_word.attrib['word_text'])
            word.save()
        # add meaning and sample sentence
        for et_meaning in et_word.findall('meaning'):
            if not word.meaning_set.filter(meaning_text=et_meaning.attrib['meaning_text']):
                et_meaning_type = et_meaning.find('meaning_type').text
                et_sample_sentence_text = et_meaning.find('sample_sentence_text').text
                word.meaning_set.create(meaning_text=et_meaning.attrib['meaning_text'], meaning_type=et_meaning_type, sample_sentence_text=et_sample_sentence_text)
    request.session['load'] = 'Words have been loaded successfully!'  # show loaded messeage at save_load_csv_file page
    return HttpResponseRedirect(reverse(('word_bank:save_load_csv_page')))

def standard_load_xml_file(request):
    all_word = Word.objects.all()
    for word in all_word:
        word.delete()

    tree = ET.parse(request.session['load'])
    words = tree.getroot()
    for et_word in words:
        if Word.objects.filter(word_text=et_word.find('text').text):  # check name objects is same already or not
            word = Word.objects.get(word_text=et_word.find('text').text)
        else:
            word = Word(word_text=et_word.find('text').text)
            word.save()
        if not word.meaning_set.filter(meaning_text=et_word.find('mean').text):
            word.meaning_set.create(meaning_text=et_word.find('mean').text, meaning_type=et_word.find('type').text, sample_sentence_text=et_word.find('ex').text)
    request.session['load'] = 'Words have been loaded successfully'  # show loaded messaged at save load_csv_file page
    return HttpResponseRedirect(reverse('word_bank:save_load_csv_page'))

def write_upload_file_for_load_word(request):
    if request.FILES != {}:  # if have file uploaded
        file = request.FILES['file']
        file_type = request.POST['file_type']
        if ('.'+file_type) not in file.name:  # file type not match with type file is uploaded
            request.session['load'] = 'type file is uploaded not match'
            return HttpResponseRedirect(reverse('word_bank:save_load_csv_page'))
        else:                                 # file type match with type file is uploaded
            if file_type == 'csv':
                dirPath = 'word_bank/static/word_bank/load_csv/'
                saveFilePath = default_storage.save(dirPath, file)
                os.rename(saveFilePath, '{}{}'.format(dirPath, file.name))
                request.session['load'] = '{}{}'.format(dirPath, file.name)
                return HttpResponseRedirect(reverse('word_bank:load_csv_file'))
            elif file_type == 'xml':
                dirPath = 'word_bank/static/word_bank/load_xml/'
                saveFilePath = default_storage.save(dirPath, file)
                os.rename(saveFilePath, '{}{}'.format(dirPath, file.name))
                request.session['load'] = '{}{}'.format(dirPath, file.name)
                #return HttpResponseRedirect(reverse('word_bank:load_xml_file'))
                return HttpResponseRedirect(reverse('word_bank:standard_load_xml_file'))
    else:
        request.session['load'] = 'No File To Upload'
        return HttpResponseRedirect(reverse('word_bank:save_load_csv_page'))  # not read file if haven't file uploaded

def save_csv_file(request):
    if request.GET.get('sort', '') :  # sort a-z
        all_word = all_word = Word.objects.order_by('word_text')
    else:
        all_word = Word.objects.all()
    fieldnames = ['word','type','meaning','sample_sentence']
    output = csv.DictWriter(open('word_bank/static/word_bank/backup_csv/word.csv','w'), fieldnames=fieldnames)
    output.writeheader()
    for word in all_word:
        output.writerow({'word':word.word_text})
        for meaning in word.meaning_set.all():
            meaning_text = smart_str(meaning.meaning_text)
            output.writerow({'word': '', 'type': meaning.meaning_type, 'meaning': meaning_text,'sample_sentence': meaning.sample_sentence_text})
    url = static('word_bank/backup_csv/word.csv')
    return HttpResponseRedirect(url)

def save_xml_file(request):
    if request.GET.get('sort', ''):  # sort a-z
        all_word = all_word = Word.objects.order_by('word_text')
    else:
        all_word = Word.objects.all()
    #request.session['load'] = 'save xml file'
    words = ET.Element('words')
    for word in all_word:
        et_word = ET.SubElement(words,'word',word_text = word.word_text)

word_bank/templates/word_bank/add_word_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Word Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>
<h1>Add Your Word</h1>
<Form action="{% url 'word_bank:add_word_page' %}" method="post">
    {% csrf_token %}
Word :<br>
<input type='text' name='word' size='40' autofocus required><br><br>
  type : <select name="meaning_type">
    <option value="n">noun</option>
    <option value="v">verb</option>
    <option value="adv">adverb</option>
    <option value="adj">adjective</option>
    <option value="prep">preposition</option>
  </select><br><br>
Meaning :<br><input type='text' name='meaning' size='40' required>
<h2>Sample Sentence :</h2>
<input type='text' name='sample_sentence'  size="40" required><br><br>

<input type='submit' value='Submit'></form><br>

{% if error_message %}
    <b>{{error_message}}</b>
{%endif%}
<br><br>
<a href="../">Back Page</a>
</body>
</html>

word_bank/templates/word_bank/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Word Detail</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>
<h1><ins>Word Detail</ins></h1>
<b>Find Word :</b> {{word.word_text}}<br><br>
       <b>Meaning : </b> {% for meaning in word.meaning_set.all %}
            <ul>
                <li>({{meaning.meaning_type}}) {{meaning.meaning_text}} : {{meaning.sample_sentence_text}}</li> <br>
                </ul>
            {%endfor%}
<br>
<a href="{%url 'word_bank:index' %}"><b>Back To Find Word Page</b></a>
</body>
</html>

word_bank/templates/word_bank/find_word.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Words List</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>

<h1><ins>Words list</ins></h1>
<h3>Find Word : {{word_search}}</h3>
{% if words %}
    {% for word in words %}
       <li> <b><a href="{% url 'word_bank:detail' word.word_text %}">{{word.word_text}}</a></b></li><br>
        {% endfor %}
{% else %}
    <b>No Results</b>
{% endif %}
</body>
</html>

word_bank/templates/word_bank/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Word Bank Online</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>
<h1><ins>Welcome to Word Bank Online</ins></h1>
<br>
<Form action="{% url 'word_bank:find_word' %}" method="get">
<b>Find Word:<br></b>
<input type='text' name='word' size='40' autofocus required>
<input type='submit' value='Submit'>
</form><br>
<b><a href="{% url 'word_bank:add_word_page' %}">Add Word Page</a></b><br><br>
<b><a href="{% url 'word_bank:show_all_word' %}">Show All Word</a></b><br><br>
<b><a href="{% url 'word_bank:save_load_csv_page' %}">Save Or Load Word With CSV File</a></b><br><br>
<b><a href="{% url 'home:home_page' %}">Home Page</a></b>

<h3><ins>4 Frequently search Word</ins></h3>
{% if all_word %}
    {% for word in all_word %}
   <li> <b><a href="{% url 'word_bank:detail' word.word_text %}">{{word.word_text}}</a></b></li><br>
    {% endfor %}
{% endif %}

<h3><ins>4 Lastest search Word</ins></h3>
{% if last_words %}
    {% for word in last_words %}
   <li> <b><a href="{% url 'word_bank:detail' word.word_text %}">{{word.word_text}}</a></b></li><br>
    {% endfor %}
{% endif %}
</body>
</html>

word_bank/templates/word_bank/save_load_csv_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Save or Load Word</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>
<h1><ins>Load Word From File(Upload)</ins></h1>

<form action="{% url 'word_bank:write_upload_file_for_load_word' %}" method="post" enctype="multipart/form-data">
             {% csrf_token %}
            Select type File:
            <select name="file_type" >
                <option value="csv" selected>csv</option>
                <option value="xml">xml</option>
            </select>
            <input type="file" name="file" id="file">
            <input type="submit"  value="Upload File" name="submit">
</form><br>
{% if request.session.load %}
    <b>{{request.session.load}}</b>
{% endif %}
<br>
<hr>
<h1><ins>Save Word to File(Download)</ins></h1>
<form>
    <input type="checkbox" name="sort" value="a-z"> sort a-z
    <input type="submit" value="Save Word To CSV File" name="submit" formaction="{% url 'word_bank:save_csv_file' %}">
    <input type="submit" value="Save Word To XML File" name="submit" formaction="{% url 'word_bank:save_xml_file' %}">
    <input type="submit" value="Save Word To Standard XML File" name="submit" formaction="{% url 'word_bank:standard_save_xml_file' %}">
</form><br>
<hr><br>
<a href="{%url 'word_bank:index' %}"><b>Back To Find Word Page</b></a>
</body>
</html>

word_bank/templates/word_bank/show_all_word.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show All Word</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'word_bank/style.css' %}" />
</head>
<body>

<h1><ins>Show All Word</ins></h1>
{% if all_word %}
    {% for word in all_word %}
   <li> <b><a href="{% url 'word_bank:detail' word.word_text %}">{{word.word_text}}</a></b></li><br>
    {% endfor %}
{% endif %}
</body>
</html>